# Generated by Django 5.0 on 2023-12-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_schoolprofilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('paystack', 'PAYSTACK'), ('flutterwave', 'FLUTTERWAVE')], max_length=250)),
                ('public_key', models.CharField(max_length=250)),
                ('private_key', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('vat', models.FloatField(default=0.0)),
                ('key', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20)),
            ],
        ),
    ]
