# Generated by Django 5.0 on 2023-12-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_onlinepaymentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolProfileModel',
        ),
    ]
