# Generated by Django 5.0 on 2023-12-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='images/logo')),
                ('mobile_1', models.CharField(max_length=20)),
                ('mobile_2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='schoolinfomodel',
            name='short_name',
            field=models.CharField(default='ff', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolinfomodel',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='images/logo'),
        ),
        migrations.DeleteModel(
            name='SchoolProfileModel',
        ),
    ]
