# Generated by Django 5.0 on 2023-12-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolformmodel_schoolinfomodel_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfomodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=30),
        ),
    ]
