# Generated by Django 5.0 on 2023-12-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_schoolinfomodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfomodel',
            name='wallet',
            field=models.FloatField(blank=0, default=0),
        ),
        migrations.DeleteModel(
            name='SchoolUserModel',
        ),
    ]
