# Generated by Django 5.0 on 2023-12-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_schoolinfomodel_wallet_delete_schoolusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldbmodel',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.schoolinfomodel'),
            preserve_default=False,
        ),
    ]
