# Generated by Django 5.0 on 2023-12-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.FloatField()),
                ('end_year', models.FloatField()),
                ('delimiter', models.CharField(choices=[('-', '-'), ('/', '/')], max_length=1)),
                ('status', models.CharField(choices=[('a', 'ACTIVE'), ('p', 'PAST'), ('n', 'NEXT')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='images/logo')),
                ('mobile_1', models.CharField(max_length=20)),
                ('mobile_2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_inactive_student', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAcademicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st TERM'), ('2nd term', '2nd TERM'), ('3rd term', '3rd TERM')], max_length=10)),
                ('next_resumption_date', models.DateField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.sessionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TermRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st TERM'), ('2nd term', '2nd TERM'), ('3rd term', '3rd TERM')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_of_schools', models.FloatField()),
                ('no_of_students', models.FloatField()),
                ('no_of_staff', models.FloatField()),
                ('no_of_parents', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.sessionmodel')),
            ],
        ),
    ]
