# Generated by Django 5.0 on 2023-12-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionmodel',
            name='status',
        ),
    ]
