# Generated by Django 5.0 on 2023-12-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_remove_sessionmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolacademicinfomodel',
            name='next_resumption_date',
        ),
        migrations.RemoveField(
            model_name='schoolacademicinfomodel',
            name='term',
        ),
    ]
