# Generated by Django 5.0 on 2023-12-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_remove_schoolacademicinfomodel_next_resumption_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolacademicinfomodel',
            name='term',
            field=models.CharField(choices=[('1st term', '1st TERM'), ('2nd term', '2nd TERM'), ('3rd term', '3rd TERM')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
